---
title: "What is the best way to promote zero calorie beverage"
format: pdf
editor: visual
fontsize: 11pt
---

## Introduction

Zero calorie beverages are healthier compared to sugared beverages because they contain less sugar and significantly fewer calories. Over the past decades, hospitals have been striving to promote zero-calorie beverages for a healthier lifestyle. This study employs five interventions to help increase such promotion. These interventions include a 10% price discount, a price discount combined with messaging that explains the reason for the discount, messaging displaying the caloric content in sugared beverages, messaging indicating the amount of exercise needed to burn off the calories in a sugared beverage, and messaging containing both caloric content and the amount of physical activity needed.

The study aims to investigate whether these interventions help encourage people to choose zero-calorie beverages over sugared beverages and if such effects are consistent across hospitals. The primary statistical question in this context is: "Is there any association between interventions and the increase in zero-calorie beverage consumption or decrease in sugary beverage consumption?" The secondary statistical question is:"Does the effect of intervention differs by site?"

## Data description and summaries

This is an experimental design where data are collected over 30 weeks, from October 27 to May 23, with a follow-up period of 14 days, gathered from two urban hospitals and one suburban hospital. During this time period, the sales of different types of drinks are recorded.

| Data Name    | Data Type   | Data Description                       |
|--------------|-------------|----------------------------------------|
| Count        | Integer     | The number of days                     |
| DofW         | Categorical | The day of the week, 7 levels          |
| Site         | Categorical | The location of the hospital, 3 levels |
| Intervention | Categorical | The intervention applied, 9 levels     |
| ZeroCal      | Integer     | The number of zero calorie drink sold  |
| Sugary       | Integer     | The number of sugary drink sold        |
| Juice100     | Integer     | The number of Juice100 sold            |
| Ojuice       | Integer     | The number of Ojuice sold              |
| Sports       | Integer     | The number of sports drink sold        |
| Total        | Continuous  | The sum of all drink sold              |

There are missing data in this dataset. The majority of missing data comes from the Juice100, Ojuice, and Sports columns, which will not be included in the model, so we can remove them. Additionally, there are 7 entirely missing consecutive entries at HF hospital during the follow-up period. This makes the assumption of missing at random valid because the hospital could be closed for construction. Other than that, there are two entirely missing entries, which are also missing at random because the hospital could be closed for a holiday.

## Conclusion

We recommend using a linear mixed-effects model and fitting two models. The first model uses ZeroCal as a response variable. Our fixed-effect explanatory variables are intervention and DofW, and our random-effect explanatory variables are Site and Total. This model will be useful to assess any association between our explanatory variables and ZeroCal. The second model uses Sugary as a response variable, with the same setup as the previous model. The second model will be ideal for demonstrating any association between the explanatory variables and Sugary.
